stages:   
  - build
  - test

build-job:
  stage: build
  script:
    - docker compose -p test -f docker-compose.test.yml down -v
    - docker compose -p test -f docker-compose.test.yml up -d --build
    - docker compose -p test -f docker-compose.test.yml ps
    - docker compose -p test -f docker-compose.test.yml logs backend

test-job:
  stage: test
  script:
    - docker compose -p test -f docker-compose.test.yml build
    - docker compose -p test -f docker-compose.test.yml up -d --wait
    - docker compose -p test -f docker-compose.test.yml run --rm backend pytest -s -v --asyncio-mode=auto 
    - EXIT_CODE=$?
    - docker compose -p test -f docker-compose.test.yml down -v
    - exit $EXIT_CODE

