version: "3.9"

networks:
  ${NETWORK_NAME}:

services:
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      retries: 10
      start_period: 30s
    tmpfs: /var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - ${NETWORK_NAME}

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    env_file:
      - ./back-end/.env
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ${NETWORK_NAME}
